nescode/urls.py
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

from django.conf.urls import patterns, include, url
from login.views import *
import login.views
import offer_letter.views
import offer_letter.emp_view
import  offer_letter.nonemp_view





admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                       url(r'^list/$', offer_letter.views.ListContactView.as_view(),name='employee-list', ),
                       url(r'^new/$', offer_letter.views.CreateEmployeeView.as_view(),
                           name='employee-new', ),
                       url(r'^edit/(?P<pk>\d+)/$', offer_letter.views.UpdateEmployeeView.as_view(),
                           name='employee-edit', ),
                       url(r'^delete/(?P<pk>\d+)/$', offer_letter.views.DeleteEmployeeView.as_view(),
                           name='employee-delete', ),
                       url(r'^candidate_details/(?P<pk>\d+)/$', offer_letter.views.EmployeeView.as_view(),
                           name='employee-view', ),
                       url(r"^(?P<pk>\d+)/offer_letter/$", offer_letter.views.offerletter.as_view(), name='get-offer',),
                            # Below is login module url like registration login logout etc.
                       #url(r'^$', index),
                       url(r'^login/$', 'django.contrib.auth.views.login',name='login'),
                       url(r'^logout/$', logout_page),
                            # If user is not login it will redirect to login page
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
                       url(r'^register/$', register),
                       url(r'^register/success/$', register_success),
                       url(r'^home/$', offer_letter.views.home,name='home'),
                            #password reset and email authentication url
                       url(r'^success/$','login.views.success_password',name="success"),
                       url(r'^update-password/$', 'login.views.reset', name='reset'),
                       url(r'^account/', include('django.contrib.auth.urls')),

                       #url(r'^reset/$', 'login.views.reset', name='reset'),
                       url(r'^password/reset/confirm/complete/$',
                                   login.views.password_reset_complete,
                                   name='password_reset_complete'), # must be named for reverse to work
                       url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                            'login.views.reset_confirm',
                            name='password_reset_confirm'),

                      #HR Module
                      url(r'human-resource/$',offer_letter.views.hr_module.as_view(),name='hr_module', ),
                      url(r'create-employee/$',offer_letter.views.register_candidate,name='register', ),
                      url(r'create-employee/success/$',offer_letter.views.employee_success,name='empployee_success', ),
                      url(r'^profile/$', 'offer_letter.emp_view.profile', name='profile'),

                      url(r'^employee/(?P<pk>\d+)/$', offer_letter.emp_view.UpdateEmployeeView.as_view(),
                           name='employee-edit1', ),
                       #for non system user
                      url(r'^new-emp/$', offer_letter.nonemp_view.CreateEmployeeView.as_view(),
                           name='employee-new2', ),
                      url(r'^emp-list/$', offer_letter.nonemp_view.ListContactView.as_view(),name='employee-list2', ),
                      url(r'^emp-details/(?P<pk>\d+)/$', offer_letter.nonemp_view.EmployeeView.as_view(),
                          name='employee-view2', ),
                      url(r'^add-emp/(?P<pk>\d+)/$', offer_letter.nonemp_view.UpdateEmployeeView.as_view(),
                           name='employee-edit2', ),
                      url(r'^delete-emp/(?P<pk>\d+)/$', offer_letter.nonemp_view.DeleteEmployeeView.as_view(),
                           name='employee-delete2', ),
                      url(r'^candidate-to-emp/$', offer_letter.nonemp_view.CreateEmployeeView1.as_view(),
                           name='employee-new3', ),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

offer_letter/models.py
from audioop import reverse
from django.db import models

#this model is for candidate profile.
class offer1(models.Model):
    salutation = models.CharField(max_length=4,
                                  choices=(('Mr', 'Mr'),
                                           ('Mrs', 'Mrs'),),blank=True,null=True,default='Select')
    name = models.CharField(max_length=100)
    empid = models.CharField(max_length=100)
    doj = models.CharField(max_length=255,blank=True,null=True)
    designation = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    supervisername = models.CharField(max_length=100)
    ctc = models.CharField(max_length=100)
    location = models.CharField(max_length=50,
                                choices=(('Bangalore', 'Bangalore'),
                                         ('New Delhi', 'New Delhi'),))
    traning_duration = models.CharField(max_length=100)
    leave = models.CharField(max_length=100)
    add1 = models.CharField(max_length=200)
    add2 = models.CharField(max_length=200)
    add3 = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('employee-view', kwargs={'pk': self.id})


# for profile picture,
from django.db import models


class ProfileImage(models.Model):
    image = models.FileField(upload_to='profile/%Y/%m/%d')

    def __unicode__(self):

        return self.image


#below model for employee  details (Employee profile)
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):

    user = models.OneToOneField(User)
    dob = models.CharField(max_length=100,blank=True, null=True,default='NA')
    presnal_email = models.CharField(max_length=100,blank=True, null=True,default='NA')
    mobile = models.CharField(max_length=100,blank=True, null=True,default='NA')
    phone = models.CharField(max_length=100,blank=True, null=True,default='NA')
    alternet_no = models.CharField(max_length=100,blank=True, null=True,default='NA')
    company = models.CharField(max_length=100,blank=True, null=True,default='NA')
    doj = models.CharField(max_length=100,blank=True, null=True,default='NA')
    department = models.CharField(max_length=100,blank=True, null=True,default='NA')
    designation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    home_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    local_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    ctc = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_leave = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_exp = models.CharField(max_length=100,blank=True, null=True,default='NA')
    employment_type = models.CharField(max_length=100,blank=True, null=True,default='NA')
    job_location  = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Passport_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Date_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Place_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Marital_Status = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Blood_Group = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Relation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    PAN_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Salary_Mode = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_Name = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_AC_No = models.CharField(max_length=100,blank=True, null=True,default='NA')
    def __str__(self):
          return "%s's profile" % self.user


    def get_absolute_url(self):
        return reverse('employee-view1', kwargs={'pk': self.id})



def create_user_profile(sender, instance, created, **kwargs):
    if created:
       profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile, sender=User)



#for employee who is not system user
class emp(models.Model):
    offer1 = models.ForeignKey(offer1)
    dob = models.CharField(max_length=100,blank=True, null=True,default='NA')
    presnal_email = models.CharField(max_length=100,blank=True, null=True,default='NA')
    mobile = models.CharField(max_length=100,blank=True, null=True,default='NA')
    phone = models.CharField(max_length=100,blank=True, null=True,default='NA')
    alternet_no = models.CharField(max_length=100,blank=True, null=True,default='NA')
    company = models.CharField(max_length=100,blank=True, null=True,default='NA')
    doj = models.CharField(max_length=100,blank=True, null=True,default='NA')
    department = models.CharField(max_length=100,blank=True, null=True,default='NA')
    designation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    home_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    local_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    ctc = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_leave = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_exp = models.CharField(max_length=100,blank=True, null=True,default='NA')
    employment_type = models.CharField(max_length=100,blank=True, null=True,default='NA')
    job_location  = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Passport_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Date_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Place_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Marital_Status = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Blood_Group = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Relation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    PAN_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Salary_Mode = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_Name = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_AC_No = models.CharField(max_length=100,blank=True, null=True,default='NA')
    def __str__(self):
        return self.offer1

    def get_absolute_url(self):
        return reverse('employee-view2', kwargs={'pk': self.id})

offer_letter/forms.py
from reportlab.lib.units import inch
from reportlab.lib import styles
from django.utils.translation import ugettext_lazy as _
from django.views.generic import UpdateView

__author__ = 'raman'
from django import forms
from offer_letter.models import offer1


class EmployeeForm(forms.ModelForm):

    name = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),label=_("Name Of Employee :"))
    empid = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),label=_("Employee Id :"))
    doj = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),label=_("Date Of Joining :"))
    designation = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                  label=_("Designation :"))
    company = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),label=_("Company :"))
    supervisername = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                    label=_("Superviser Name :"))
    ctc = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),label=_("CTC :"))
    traning_duration = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                        label=_("Traning Duration :"))
    leave = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                        label=_("Leave :"))
    add1 = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                        label=_("Address Line 1 :"))
    add2 = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                        label=_("Address Line 2 :"))
    add3 = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                        label=_("Address Line 3 :"))

    class Meta:
        model = offer1



# for creating candidate as employee

from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class RegistrationForm(forms.Form):
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                                label=_("User Name"), error_messages={
            'invalid': _("This value must contain only letters, numbers and underscores.")})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email Address"))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password (again)"))


    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data


#employee with system user form.
from offer_letter.models import UserProfile
from django.utils.translation import ugettext_lazy as _
class employee_profile(forms.ModelForm):
    doj = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30,)),label=_(" doj"))
    class Meta:
        model = UserProfile


#employee without system user form
from offer_letter.models import  emp
class emp_profile(forms.ModelForm):
    doj = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30,)),label=_(" doj"))
    class Meta:
        model = emp

offer_letter/templates/add_employee_details.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block offer %}
<form action="." method="POST" role="form">{% csrf_token %}
{{form.as_ul}}
 <button type="submit" class="btn btn-primary btn-xs" id="save_contact" >Save</button>
                <a href="/list" class="btn btn-default btn-xs">Back</a>
</form>
{% endblock %}

offer_letter/templates/edit_employee.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block offer %}
     <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<form action="{{ action }}" method="POST" role="form">{% csrf_token %}
<div class="container">
 <div class="col-md-11">
     <!--Main panel Start here-->
            <div class="panel panel-default">
                <div class="panel-heading"><span class="glyphicon glyphicon-hand-right"></span> Human Resource
                </div>
                <div class="panel-body">
                     <div class="col-md-1">
                            <!--<ul class="nav nav-pills nav-stacked">-->

                              <!--<li><a href="#"><span class="glyphicon glyphicon-user">-->

                              <!--</span> Candidate</a></li>-->

                            <!--</ul>-->
                     </div>
                     <div class="col-md-11">
		<div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-user"></span> Add Candidate

            </div>
            <div class="well well-sm">
                <button type="submit" class="btn btn-default btn-xs" id="save_contact" >Save</button>
                <a href="/list" class="btn btn-default btn-xs">Back</a>
            </div>


					<div class="panel-body">
                            <!-- employee informations -->
                            <div class="col-sm-6">
                                <!-- employee information first row Start-->
                                <div class="panel-body form-horizontal">


                                    <div class="form-group">
                                            <label for="id_salutation" class="col-sm-4 control-label">Salutation</label>
                                            <div class="col-sm-6">
                                                <div class="dropdown">
                                                     <select id="id_salutation" name="salutation"
                                                             class="form-control">
                                                         {% if offer1.id %}
                                                    <option>{{ offer1.salutation }}</option>
                                                    <option value="Mr">Mr</option>
                                                    <option value="Mrs">Mrs</option>
                                                         {% else %}
                                                     <option value="">Select</option>
                                                    <option value="Mr">Mr</option>
                                                    <option value="Mrs">Mrs</option>
                                                         {% endif %}
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    <div class="form-group">
                                           <label for="id_name" class="col-sm-4 control-label" >Name </label>
                                            <div class="col-sm-8">
                                                <input  class="form-control" id="id_name" max_length="30"
                                                               name="name" required="True" type="text"
                                                               value="{{ offer1.name }}"  />
                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_empid" class="col-sm-4 control-label">Candidate Id </label>
                                            <div class="col-sm-8">
                                                <input class="form-control"id="id_empid" max_length="30" name="empid" required="True"
                                                          type="text" value="{{ offer1.empid }}" />
                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_doj" class="col-sm-4 control-label">Date Of Joining </label>
                                            <div class="col-sm-8" >
                                                <input class="form-control"id="id_doj" max_length="30" name="doj" required="True"
                                                            type="text" value="{{ offer1.doj }}"
                                                            placeholder="YY-MM-DD" />
                                                                                                    <script type="text/javascript">
                                                                                                     $(function() {
                                                                                                         $("#id_doj").datepicker({ dateFormat: "yy-mm-dd" }).val()
                                                                                                     })</script>

                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_designation" class="col-sm-4 control-label">Apply for the post
                                           </label>
                                            <div class="col-sm-8">
                                                <input class="form-control"id="id_designation" max_length="30" name="designation"
                                                                required="True" type="text" value="{{ offer1.designation }}" />
                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_company" class="col-sm-4 control-label">Company </label>
                                            <div class="col-sm-8">
                                                <input id="id_company" class="form-control"max_length="30" name="company" required="True"
                                                        type="text" value="{{ offer1.company }}" />
                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_supervisername" class="col-sm-4 control-label">HR
                                           Name</label>
                                            <div class="col-sm-8">
                                                <input id="id_supervisername"class="form-control" max_length="30"
                                                                       name="supervisername" required="True" type="text"
                                                                       value="{{ offer1.supervisername }}" />
                                            </div>
                                    </div>
                                </div>

                                                    </div>
                                            {% if form.errors %}
                             <div style="text-align: center">
                             <p>Error :- Please Select Location.</p>
                         {% endif %}
                            <!-- employee information first row End-->

                            <!--employee information row second Row Start-->

                            <div class="col-sm-6">
                                <div class="panel-body form-horizontal">
                                    <div class="form-group">
                                           <label for="id_ctc" class="col-sm-4 control-label"> Expected CTC </label>
                                            <div class="col-sm-8">
                                                <input id="id_ctc" max_length="30" name="ctc" required="True" class="form-control"type="text"
                                            value="{{ offer1.ctc }}" placeholder="Amount /- Annum" />
                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_location" class="col-sm-4 control-label">Branch</label>
                                            <div class="col-sm-6">
                                                <select id="id_location" name="location" class="form-control">
                                                    {% if offer1.id %}
                                                    <option>{{ offer1.location }}</option>
                                                    <option value="Bangalore">Bangalore</option>
                                                    <option value="New Delhi">New Delhi</option>
                                                         {% else %}
                                                <option value="{{ offer1.location }}">Select</option>
                                                <option value="Bangalore" >Bangalore</option>
                                                <option value="New Delhi">New Delhi</option>
                                                    {% endif %}
                                                </select>
                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_traning_duration"class="col-sm-4 control-label">Probationary Period </label>
                                            <div class="col-sm-8">
                                                <input id="id_traning_duration" max_length="30"
                                                                      name="traning_duration" required="True"class="form-control"
                                                                      type="text" value="{{ offer1.traning_duration }}" />

                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_leave"class="col-sm-4 control-label">Leave </label>
                                            <div class="col-sm-8">
                                               <input id="id_leave" max_length="30" name="leave" required="True"
                                                type="text" value="{{ offer1.leave }}" class="form-control"/>
                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_add1"class="col-sm-4 control-label">Address Line 1 </label>
                                            <div class="col-sm-8">
                                                <input id="id_add1" max_length="30" name="add1" required="True"
                                                        type="text" value="{{ offer1.add1 }}" class="form-control"/>

                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_add2" class="col-sm-4 control-label">Address Line 2 </label>
                                            <div class="col-sm-8">
                                                <input id="id_add2" max_length="30" name="add2" required="True"
                                                        type="text" value="{{ offer1.add2 }}" class="form-control"/>

                                            </div>
                                    </div>
                                    <div class="form-group">
                                           <label for="id_add3"class="col-sm-4 control-label">Address Line 3 </label>
                                            <div class="col-sm-8">
                                                 <input id="id_add3" max_length="30" name="add3" required="True"
                                                        type="text" value="{{ offer1.add3 }}" class="form-control"/>

                                            </div>
                                    </div>
                                </div>

                            </div>

                        </div>
				</div>
        </div>
    </div>
                 </div>
            </div>
          </div>

</div>

</form>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'nescode.js' %}"></script>
{% endblock %}