nescode/urls.py
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

from django.conf.urls import patterns, include, url
from login.views import *
import login.views
import offer_letter.views
import offer_letter.emp_view
import  offer_letter.nonemp_view





admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                       url(r'^list/$', offer_letter.views.ListContactView.as_view(),name='employee-list', ),
                       url(r'^new/$', offer_letter.views.CreateEmployeeView.as_view(),
                           name='employee-new', ),
                       url(r'^edit/(?P<pk>\d+)/$', offer_letter.views.UpdateEmployeeView.as_view(),
                           name='employee-edit', ),
                       url(r'^delete/(?P<pk>\d+)/$', offer_letter.views.DeleteEmployeeView.as_view(),
                           name='employee-delete', ),
                       url(r'^candidate_details/(?P<pk>\d+)/$', offer_letter.views.EmployeeView.as_view(),
                           name='employee-view', ),
                       url(r"^(?P<pk>\d+)/offer_letter/$", offer_letter.views.offerletter.as_view(), name='get-offer',),
                            # Below is login module url like registration login logout etc.
                       #url(r'^$', index),
                       url(r'^login/$', 'django.contrib.auth.views.login',name='login'),
                       url(r'^logout/$', logout_page),
                            # If user is not login it will redirect to login page
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
                       url(r'^register/$', register),
                       url(r'^register/success/$', register_success),
                       url(r'^home/$', offer_letter.views.home,name='home'),
                            #password reset and email authentication url
                       url(r'^success/$','login.views.success_password',name="success"),
                       url(r'^update-password/$', 'login.views.reset', name='reset'),
                       url(r'^account/', include('django.contrib.auth.urls')),

                       #url(r'^reset/$', 'login.views.reset', name='reset'),
                       url(r'^password/reset/confirm/complete/$',
                                   login.views.password_reset_complete,
                                   name='password_reset_complete'), # must be named for reverse to work
                       url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                            'login.views.reset_confirm',
                            name='password_reset_confirm'),

                      #HR Module
                      url(r'human-resource/$',offer_letter.views.hr_module.as_view(),name='hr_module', ),
                      url(r'create-employee/$',offer_letter.views.register_candidate,name='register', ),
                      url(r'create-employee/success/$',offer_letter.views.employee_success,name='empployee_success', ),
                      url(r'^profile/$', 'offer_letter.emp_view.profile', name='profile'),

                      url(r'^employee/(?P<pk>\d+)/$', offer_letter.emp_view.UpdateEmployeeView.as_view(),
                           name='employee-edit1', ),
                       #for non system user
                      url(r'^new-emp/$', offer_letter.nonemp_view.CreateEmployeeView.as_view(),
                           name='employee-new2', ),
                      url(r'^emp-list/$', offer_letter.nonemp_view.ListContactView.as_view(),name='employee-list2', ),
                      url(r'^emp-details/(?P<pk>\d+)/$', offer_letter.nonemp_view.EmployeeView.as_view(),
                          name='employee-view2', ),
                      url(r'^add-emp/(?P<pk>\d+)/$', offer_letter.nonemp_view.UpdateEmployeeView.as_view(),
                           name='employee-edit2', ),
                      url(r'^delete-emp/(?P<pk>\d+)/$', offer_letter.nonemp_view.DeleteEmployeeView.as_view(),
                           name='employee-delete2', ),
                      url(r'^candidate-to-emp/$', offer_letter.nonemp_view.CreateEmployeeView1.as_view(),
                           name='employee-new3', ),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

offer_letter/models.py
from audioop import reverse
from django.db import models

#this model is for candidate profile.
class offer1(models.Model):
    salutation = models.CharField(max_length=4,
                                  choices=(('Mr', 'Mr'),
                                           ('Mrs', 'Mrs'),),blank=True,null=True,default='Select')
    name = models.CharField(max_length=100)
    empid = models.CharField(max_length=100)
    doj = models.CharField(max_length=255,blank=True,null=True)
    designation = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    supervisername = models.CharField(max_length=100)
    ctc = models.CharField(max_length=100)
    location = models.CharField(max_length=50,
                                choices=(('Bangalore', 'Bangalore'),
                                         ('New Delhi', 'New Delhi'),))
    traning_duration = models.CharField(max_length=100)
    leave = models.CharField(max_length=100)
    add1 = models.CharField(max_length=200)
    add2 = models.CharField(max_length=200)
    add3 = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('employee-view', kwargs={'pk': self.id})


# for profile picture,
from django.db import models


class ProfileImage(models.Model):
    image = models.FileField(upload_to='profile/%Y/%m/%d')

    def __unicode__(self):

        return self.image


#below model for employee  details (Employee profile)
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):

    user = models.OneToOneField(User)
    dob = models.CharField(max_length=100,blank=True, null=True,default='NA')
    presnal_email = models.CharField(max_length=100,blank=True, null=True,default='NA')
    mobile = models.CharField(max_length=100,blank=True, null=True,default='NA')
    phone = models.CharField(max_length=100,blank=True, null=True,default='NA')
    alternet_no = models.CharField(max_length=100,blank=True, null=True,default='NA')
    company = models.CharField(max_length=100,blank=True, null=True,default='NA')
    doj = models.CharField(max_length=100,blank=True, null=True,default='NA')
    department = models.CharField(max_length=100,blank=True, null=True,default='NA')
    designation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    home_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    local_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    ctc = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_leave = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_exp = models.CharField(max_length=100,blank=True, null=True,default='NA')
    employment_type = models.CharField(max_length=100,blank=True, null=True,default='NA')
    job_location  = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Passport_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Date_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Place_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Marital_Status = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Blood_Group = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Relation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    PAN_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Salary_Mode = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_Name = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_AC_No = models.CharField(max_length=100,blank=True, null=True,default='NA')
    def __str__(self):
          return "%s's profile" % self.user


    def get_absolute_url(self):
        return reverse('employee-view1', kwargs={'pk': self.id})



def create_user_profile(sender, instance, created, **kwargs):
    if created:
       profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile, sender=User)



#for employee who is not system user
class emp(models.Model):
    offer1 = models.ForeignKey(offer1)
    dob = models.CharField(max_length=100,blank=True, null=True,default='NA')
    presnal_email = models.CharField(max_length=100,blank=True, null=True,default='NA')
    mobile = models.CharField(max_length=100,blank=True, null=True,default='NA')
    phone = models.CharField(max_length=100,blank=True, null=True,default='NA')
    alternet_no = models.CharField(max_length=100,blank=True, null=True,default='NA')
    company = models.CharField(max_length=100,blank=True, null=True,default='NA')
    doj = models.CharField(max_length=100,blank=True, null=True,default='NA')
    department = models.CharField(max_length=100,blank=True, null=True,default='NA')
    designation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    home_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    local_address = models.CharField(max_length=100,blank=True, null=True,default='NA')
    ctc = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_leave = models.CharField(max_length=100,blank=True, null=True,default='NA')
    total_exp = models.CharField(max_length=100,blank=True, null=True,default='NA')
    employment_type = models.CharField(max_length=100,blank=True, null=True,default='NA')
    job_location  = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Passport_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Date_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Place_of_Issue = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Marital_Status = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Blood_Group = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Relation = models.CharField(max_length=100,blank=True, null=True,default='NA')
    PAN_Number = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Salary_Mode = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_Name = models.CharField(max_length=100,blank=True, null=True,default='NA')
    Bank_AC_No = models.CharField(max_length=100,blank=True, null=True,default='NA')
    def __str__(self):
        return self.offer1

    def get_absolute_url(self):
        return reverse('employee-view2', kwargs={'pk': self.id})

offer_letter/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import password_reset
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView
from easy_pdf.views import PDFTemplateView
from offer_letter import forms
from offer_letter.forms import RegistrationForm
from offer_letter.models import offer1


class ListContactView(ListView):
    model = offer1
    template_name = 'candidate_list.html'

    #this is for login required ..without login u can't go to this page
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ListContactView, self).dispatch(*args, **kwargs)


from django.core.urlresolvers import reverse
from django.views.generic import CreateView

#inserting of data through this create employee view class.

class CreateEmployeeView(CreateView):
    model = offer1
    template_name = 'edit_employee.html'

    form_class = forms.EmployeeForm
    #this is for login required ..without login u can't go to this page
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CreateEmployeeView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('employee-list')

    def get_context_data(self, **kwargs):
        context = super(CreateEmployeeView, self).get_context_data(**kwargs)
        context['action'] = reverse('employee-new')

        return context


#Updating of data through this create employee view class.

from django.views.generic import UpdateView


class UpdateEmployeeView(UpdateView):
    model = offer1
    template_name = 'edit_employee.html'
    form_class = forms.EmployeeForm
    #this is for login required ..without login u can't go to this page
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UpdateEmployeeView, self).dispatch(*args, **kwargs)


    def get_success_url(self):

        return reverse('employee-list',)

    def get_context_data(self, **kwargs):
        context = super(UpdateEmployeeView, self).get_context_data(**kwargs)
        context['action'] = reverse('employee-edit',kwargs={'pk':self.get_object().id})

        return context
#delete data from data base.
from django.views.generic import DeleteView


class DeleteEmployeeView(DeleteView):
    model = offer1
    template_name = 'delete_employee.html'


    #this is for login required ..without login u can't go to this page
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeleteEmployeeView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('employee-list')


#employee full details.
from django.views.generic import DetailView


class EmployeeView(DetailView):
    model = offer1

    template_name = 'candidate_profile.html'

    #this is for login required ..without login u can't go to this page
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(EmployeeView, self).dispatch(*args, **kwargs)



#pdf generation using easy pdf.
class offerletter(PDFTemplateView):
    model = offer1
    template_name = "employee.html"


    #this is for login required ..without login u can't go to this page
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(offerletter, self).dispatch(*args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super(offerletter, self).get_context_data(
            pagesize="A4",
            title="Offer Letter",


            **kwargs)

        if 'pk' in self.kwargs:
            context['tool'] = offer1.objects.get(id=self.kwargs['pk'])

            return context
        def get_success_url(self):
            return reverse('get-pdf')

class hr_module(ListView):
    model = offer1
    template_name = 'HR/hr_module.html'

    #this is for login required ..without login u can't go to this page
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(hr_module, self).dispatch(*args, **kwargs)




@login_required
def home(request):
    return password_reset(request, template_name='home.html',
        post_reset_redirect=reverse('success'))


# for making candidate as an employee we have to register that candidate in our application.


@csrf_protect
def register_candidate(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']

            )
            return HttpResponseRedirect('/create-employee/success/')
    else:
        form = RegistrationForm()
    variables = RequestContext(request, {
    'form': form
    })

    return render_to_response(
    'register-candidate.html',
    variables,
    )
@login_required
def employee_success(request):
    return password_reset(request, template_name='register-candidate-success.html',
        post_reset_redirect=reverse('success'))

offer_letter/templates/HR/candidate_to_emp.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block offer %}
     <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<form action="{{ action }}" method="POST" role="form">{% csrf_token %}
<div class="container">
 <div class="col-md-11">
     <!--Main panel Start here-->
            <div class="panel panel-default">
                <div class="panel-heading"><span class="glyphicon glyphicon-hand-right"></span> Human Resource
                </div>
                <div class="panel-body">
                     <div class="col-md-3">
                            <ul class="nav nav-pills nav-stacked">

                              <li class="active"><a href="#"><span class="glyphicon glyphicon-user">

                              </span> Candidate To Employee</a></li>

                            </ul>
                     </div>
                     <div class="col-md-9">
		<div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-user"></span> Make Candidate as Employee

            </div>
            <div class="well well-sm">
                <p class="text-danger">
                        For making candidate as employee Please Select Candidate and click yes  else click no.
                    </p>
            </div>

					<div class="panel-body">

                            <!-- employee informations -->
                 <div class="row">


                        <div class="col-md-12">
                        <div class="form-group">
                                            <label for="id_offer1" class="col-sm-3 control-label">
                                               Candidate Name:</label>
                                            <div class="col-sm-4">
                                                <div class="dropdown">

                                                    <select id="id_offer1" name="offer1"
                                                             class="form-control" value="{{form.offer1}}
                                                    </select>

                                                </div>
                                            </div>
                                        </div>
                        </div>
                     <p>&nbsp;</p>
                     <p class="text-center">
                     <button type="submit" class="btn btn-default btn-sm" id="save_contact" >Yes</button>
                <a href="/list" class="btn btn-default btn-sm"> No,Cancle</a></p>
                    </div>
            </div>
</div>

</form>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'nescode.js' %}"></script>
{% endblock %}

offer_letter/templates/HR/delete_emp.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block offer %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!--container start here-->
<div class="container">
  <div class="col-md-11">
     <!--Main panel Start here-->
            <div class="panel panel-default">
                <div class="panel-heading"><span class="glyphicon glyphicon-hand-right"></span> Human Resource
                </div>
                <div class="panel-body">
                    <div class="col-md-2">
                            <ul class="nav nav-pills nav-stacked">

                              <li class="active"><a href="#"><span class="glyphicon glyphicon-user">

                              </span> Employee</a></li>

                            </ul>
                     </div>
    <div class="col-md-10">
        <!--panel start here-->
		<div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-user"></span> Are you sure to delete this
                Employee
            </div>

                        <div class="panel-body">
                            <!-- panel body start here -->
                            <div class="col-sm-6">
                                <h4>Delete Employee  {{ emp.offer1 }}  ?</h4>
                                        <form action="{% url "employee-delete2" pk=emp.id %}" method="POST">
                                          {% csrf_token %}
                                          <input type="submit" class="btn btn-danger btn-xs" value="Yes, delete." />
                                          <a class="btn btn-default btn-xs" href=
                                                  "{% url "employee-list2" %}">No, cancel.</a>
                                        </form>
                            </div>
                            <!-- panel body end here -->
                        </div>
                    </div>
                </div>
                   </div>
            </div>
          </div>

      </div>

<!--container end here-->
    <!--Java script calling tag  -->
{% endblock %}

offer_letter/templates/HR/emp_list.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block offer %}
<script src="{% static 'nescode.js' %}"></script>
     <link href="{% static 'nescode.css' %}" rel="stylesheet" media="screen">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
     <script src="{% static 'dist/js/myjs.js' %}"></script>
     <script src="../../static/dist/js/npm.js"></script>
    <script src="../../static/dist/js/bootstrap.js"></script>
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'nescode.js' %}"></script>
     <!-- container  Start here-->
<div class="container">
    <div class="col-md-11">
     <!--Main panel Start here-->
		<div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-hand-right"></span> Human Resource
                </div>
        				 <!-- panel body start here-->
						<div class="panel-body">

                                <div class="col-sm-2">
                            <ul class="nav nav-pills nav-stacked">

                              <li><a href="/list"><span class="glyphicon glyphicon-transfer">

                              </span> Recruitment</a></li>
                                <li class="active"><a href="#"><span class="glyphicon glyphicon-user">

                              </span> Employee</a></li>

                            </ul>
                                </div>

                            <div class="col-md-10" >
                                  <!--inside panel second panel Start here-->
									<div class="panel panel-default">
											<div class="panel-heading">
                                                	<h3 class="panel-title">Employee list</h3>
                                        <div class="pull-right" style="padding-top:16px">
                                            <div class="dropdown">
                                              <button class="btn  btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                      aria-expanded="true">
                                                <span class="glyphicon glyphicon-th-list"></span>
                                              </button>
                                              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                                <li role="presentation"><a role="menuitem" tabindex="-1"
                                                                           href="{% url "employee-new2" %}">Add
                                                    Employee</a></li>
                                                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Employee
                                                </a></li>
                                              </ul>
                                            </div>
                                        </div>

           									</div>
											<div class="panel-body">
												<input type="text" class="form-control" id="task-table-filter" data-action="filter"
													   data-filters="#task-table" placeholder="Search Employee By Name Or Employee Id" />

											<table class="table table-hover" id="task-table">
												<thead>
													<tr>
														<th>#</th>
														<th>Name</th>
														<th>Employee Id</th>
														<th>Post</th>
                                                        <th>Joining Date</th>
													</tr>
												</thead>
												<tbody>
												{% for emp in object_list %}
													<tr>
														<td>#</td>
														<td>
                                                            <a href="{% url "employee-view2" pk=emp.id%}">
                                                            {{emp.offer1}}</a></td>
														<td>EMP/NC/00{{ emp.id }}</td>
														<td>{{ emp.designation }}</td>
                                                        <td>{{ emp.doj}}</td></a>
													</tr>
													{% endfor %}
												</tbody>
											</table>
										</div>
									</div>
                                 	<!--inside panel second panel end here-->
                                 </div>


                        </div>
					</div>
        				<!-- panel body end here-->
                        </div>
    <!-- panel Start here-->
        </div>
    </div>
</div>
    <!--Java script calling tag  -->
{% endblock %}

offer_letter/templates/HR/hr_module.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block offer %}
<script src="{% static 'nescode.js' %}"></script>
     <link href="{% static 'nescode.css' %}" rel="stylesheet" media="screen">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
     <script src="{% static 'dist/js/myjs.js' %}"></script>
     <script src="../../static/dist/js/npm.js"></script>
    <script src="../../static/dist/js/bootstrap.js"></script>
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'nescode.js' %}"></script>
     <!-- container  Start here-->
<div class="container">
    <div class="col-md-11">
     <!--Main panel Start here-->
		<div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-hand-right"></span> Human Resource
                </div>
        				 <!-- panel body start here-->
						<div class="panel-body">

                                <div class="col-sm-2">
                            <ul class="nav nav-pills nav-stacked">

                              <li><a href="/list"><span class="glyphicon glyphicon-transfer">

                              </span> Recruitment</a></li>
                              <li><a href="/emp-list"><span class="glyphicon glyphicon-user">

                              </span> Employee</a></li>
                            </ul>
                                    <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
                                </div>



					</div>
        				<!-- panel body end here-->
                        </div>
    <!-- panel Start here-->
        </div>
</div>

    <!--Java script calling tag  -->

{% endblock %}